import { NextPage, GetStaticProps } from "next";
import Head from "next/head";

type Props = {
  serverDate: string;
};

const Sample: NextPage<Props> = ({ serverDate }) => {
  return (
    <>
      <Head>
        <title>Server Timezone Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-stone-50 mx-auto h-screen text-center">
        <h1 className="text-2xl mt-10 inline-block">
          Server Timezone Checksaa
        </h1>
        <p>{serverDate}</p>
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = () => {
  // nodeサーバのタイムゾーンの動作確認
  return {
    props: {
      serverDate: Date(),
    },
  };
};

export default Sample;
